# Generated by Django 3.0.3 on 2020-02-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shops',
            new_name='Shop',
        ),
    ]
