# Generated by Django 3.0.3 on 2020-02-20 15:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20200220_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326),
        ),
    ]
